### ISSUE TITLE
Syncing breaks when client resets connection

### ISSUE THREAD

**Issue by shelbyd** [voltrb/volt#124]
Reproduction:

1. Connect two devices to the same site (sharing a store)
1. Refresh the page on one device
1. Do something on the not refreshed device that would update the refreshed device

Observed: Refreshed device does not update
Expected: Refreshed device updates

The server also throws the following stack trace:

```
E, [2015-03-16T02:47:07.625049 #3] ERROR -- : undefined method `delete' for nil:NilClass (NoMethodError) 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/utils/generic_pool.rb:84:in `block in remove' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/utils/generic_pool.rb:80:in `each' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/utils/generic_pool.rb:80:in `each_with_index' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/utils/generic_pool.rb:80:in `remove' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/live_query.rb:70:in `remove_channel' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/query_tasks.rb:58:in `block in close!' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/query_tasks.rb:57:in `each' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/query_tasks.rb:57:in `close!' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/server/socket_connection_handler.rb:61:in `closed' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/server/socket_connection_handler.rb:53:in `rescue in send_message' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/server/socket_connection_handler.rb:47:in `send_message' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/live_query.rb:49:in `block in notify_changed' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/live_query.rb:83:in `block in notify!' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/live_query.rb:82:in `each' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/live_query.rb:82:in `notify!' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/live_query.rb:48:in `notify_changed' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/query_tracker.rb:88:in `block in detect_changed' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/query_tracker.rb:85:in `each' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/query_tracker.rb:85:in `detect_changed' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/query_tracker.rb:39:in `process_changes' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/query_tracker.rb:29:in `run' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/live_query.rb:22:in `run' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/live_query_pool.rb:18:in `block in updated_collection' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/live_query_pool.rb:17:in `each' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/live_query/live_query_pool.rb:17:in `updated_collection' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/models/persistors/model_store.rb:207:in `save_to_db!' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/models/persistors/model_store.rb:94:in `changed' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/models/model.rb:98:in `attributes=' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/models/buffer.rb:16:in `save!' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/app/volt/tasks/store_tasks.rb:48:in `save' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/tasks/dispatcher.rb:27:in `block in dispatch' 
/app/vendor/bundle/ruby/2.1.0/gems/opal-0.6.3/stdlib/promise.rb:93:in `call' 
/app/vendor/bundle/ruby/2.1.0/gems/opal-0.6.3/stdlib/promise.rb:93:in `resolve' 
/app/vendor/bundle/ruby/2.1.0/gems/opal-0.6.3/stdlib/promise.rb:69:in `>>' 
/app/vendor/bundle/ruby/2.1.0/gems/opal-0.6.3/stdlib/promise.rb:52:in `^' 
/app/vendor/bundle/ruby/2.1.0/gems/opal-0.6.3/stdlib/promise.rb:158:in `then' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/tasks/dispatcher.rb:24:in `dispatch' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-0.8.26/lib/volt/server/socket_connection_handler.rb:41:in `process_message' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-sockjs-0.3.4.4/lib/sockjs/session.rb:252:in `block in run_user_app' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-sockjs-0.3.4.4/lib/sockjs/session.rb:250:in `each' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-sockjs-0.3.4.4/lib/sockjs/session.rb:250:in `run_user_app' 
/app/vendor/bundle/ruby/2.1.0/gems/volt-sockjs-0.3.4.4/lib/sockjs/session.rb:222:in `block in receive_message' 
/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:968:in `call' 
/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:968:in `block in run_deferred_callbacks' 
/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:965:in `times' 
/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:965:in `run_deferred_callbacks' 
/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine' 
/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run' 
/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start' 
/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start' 
/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.3/lib/thin/controllers/controller.rb:87:in `start' 
/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command' 
/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!' 
/app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.3/bin/thin:6:in `<top (required)>' 
/app/vendor/bundle/ruby/2.1.0/bin/thin:23:in `load' 
/app/vendor/bundle/ruby/2.1.0/bin/thin:23:in `<main>' 
```

**Comment by ryanstout** [comment]
This should be fixed in 0.9.1.pre2 (gem install volt --pre)  Let me know if its not.  Thanks!

**Comment by shelbyd** [comment]
Can't verify with 0.9.1.pre2. Upon starting the server I get a 500 and the following stack trace:

```
NoMethodError: undefined method `+' for nil:NilClass
/home/username/.rvm/gems/ruby-2.1.3/gems/volt-0.9.1.pre2/lib/volt/server/rack/http_resource.rb:38:in `dispatch_to_controller'
/home/username/.rvm/gems/ruby-2.1.3/gems/volt-0.9.1.pre2/lib/volt/server/rack/http_resource.rb:20:in `call'
/home/username/.rvm/gems/ruby-2.1.3/gems/volt-0.9.1.pre2/lib/volt/server/rack/index_files.rb:37:in `call'
/home/username/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
/home/username/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
/home/username/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
/home/username/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
/home/username/.rvm/gems/ruby-2.1.3/gems/volt-0.9.1.pre2/lib/volt/server/rack/quiet_common_logger.rb:10:in `call'
/home/username/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
/home/username/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
/home/username/.rvm/gems/ruby-2.1.3/gems/volt-0.9.1.pre2/lib/volt/server.rb:36:in `call'
/home/username/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
/home/username/.rvm/gems/ruby-2.1.3/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
/home/username/.rvm/gems/ruby-2.1.3/gems/volt-0.9.1.pre2/lib/volt/server/forking_server.rb:98:in `call_on_child'
/home/username/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/drb/drb.rb:1588:in `perform_without_block'
/home/username/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/drb/drb.rb:1548:in `perform'
/home/username/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/drb/drb.rb:1626:in `block (2 levels) in main_loop'
/home/username/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/drb/drb.rb:1622:in `loop'
/home/username/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/drb/drb.rb:1622:in `block in main_loop'
```

**Comment by ryanstout** [comment]
@shelbyd any chance you can push the repo up to github so I can see what's going on?  Is this a new project or an updated one?  Thanks!

**Comment by shelbyd** [comment]
The repository is open source right here: https://github.com/shelbyd/remotrospective

**Comment by ryanstout** [comment]
@shelbyd awesome, checking it out, one sec

**Comment by ryanstout** [comment]
this project is on 0.8.26, am I on the right branch?

**Comment by ryanstout** [comment]
or should I update and try it?

**Comment by shelbyd** [comment]
I updated it locally with volt#0.9.1.pre2 on ruby-2.1.3.

**Comment by ryanstout** [comment]
@shelbyd did you have things running on 0.9.0 before?  In the repo I saw, you need to update the routes.rb file.  (Change get to client, remove _'s)

https://github.com/voltrb/volt/blob/master/CHANGELOG.md

**Comment by shelbyd** [comment]
Apparently I have a bit of work to do to upgrade to 0.9 before I can verify the fix. I'll do that and let you know how it goes.

**Comment by ryanstout** [comment]
@shelbyd sorry, we had quite a few breaking changes from 0.8 to 0.9.  Should be the last batch of big breaking changes.  The CHANGELOG will help, and here: http://blog.voltframework.com/post/117031476149/volt-0-9-0-is-here-and-its-amazing  Thanks!

**Comment by shelbyd** [comment]
After upgrading to 0.9 this problem seems to be fixed. Good work @ryanstout!
