### ISSUE TITLE
model.destroy raises a "wrong number of args" error with v-0.9.1

### ISSUE THREAD

**Issue by mathieul** [voltrb/volt#194]
I've upgraded my application to *0.9.1* and now calling `model.destroy` from a view (`<button e-click="task.destroy">`) raises a "wrong number of arguments" error in the mongo driver data store.

I've tested with older versions as well, and note that it is working fine in *0.9.1-pre4* but fails also in *0.9.1-pre5*.

Here is the stack trace:

```
wrong number of arguments (1 for 2)
/path/to/ruby/gems/2.2.0/gems/volt-0.9.1/lib/volt/data_stores/mongo_driver.rb:60:in `delete'
/path/to/ruby/gems/2.2.0/gems/volt-0.9.1/app/volt/tasks/store_tasks.rb:80:in `block in delete'
/path/to/ruby/gems/2.2.0/gems/opal-0.7.2/stdlib/promise.rb:192:in `call'
/path/to/ruby/gems/2.2.0/gems/opal-0.7.2/stdlib/promise.rb:192:in `resolve'
/path/to/ruby/gems/2.2.0/gems/volt-0.9.1/lib/volt/utils/promise_patch.rb:24:in `>>'
/path/to/ruby/gems/2.2.0/gems/opal-0.7.2/stdlib/promise.rb:151:in `^'
/path/to/ruby/gems/2.2.0/gems/opal-0.7.2/stdlib/promise.rb:261:in `then'
/path/to/ruby/gems/2.2.0/gems/volt-0.9.1/lib/volt/models/array_model.rb:156:in `fetch_first'
/path/to/ruby/gems/2.2.0/gems/volt-0.9.1/app/volt/tasks/store_tasks.rb:77:in `delete'
/path/to/ruby/gems/2.2.0/gems/volt-0.9.1/lib/volt/tasks/dispatcher.rb:38:in `block in dispatch'
/path/to/ruby/gems/2.2.0/gems/opal-0.7.2/stdlib/promise.rb:192:in `call'
/path/to/ruby/gems/2.2.0/gems/opal-0.7.2/stdlib/promise.rb:192:in `resolve'
/path/to/ruby/gems/2.2.0/gems/volt-0.9.1/lib/volt/utils/promise_patch.rb:24:in `>>'
/path/to/ruby/gems/2.2.0/gems/opal-0.7.2/stdlib/promise.rb:151:in `^'
/path/to/ruby/gems/2.2.0/gems/opal-0.7.2/stdlib/promise.rb:261:in `then'
/path/to/ruby/gems/2.2.0/gems/volt-0.9.1/lib/volt/tasks/dispatcher.rb:32:in `dispatch'
/path/to/ruby/2.2.0/drb/drb.rb:1624:in `perform_without_block'
/path/to/ruby/2.2.0/drb/drb.rb:1584:in `perform'
/path/to/ruby/2.2.0/drb/drb.rb:1657:in `block (2 levels) in main_loop'
/path/to/ruby/2.2.0/drb/drb.rb:1653:in `loop'
/path/to/ruby/2.2.0/drb/drb.rb:1653:in `block in main_loop'
```

Thanks,

Mathieu

**Comment by ryanstout** [comment]
This one slipped through the cracks some how.  (we were testing the old way to delete records) Spec added, and 0.9.2 released to fix it.

**Comment by mathieul** [comment]
Wow, that was fast!

Thanks much.
