### ISSUE TITLE
Errno::ENOENT for druby on 0.9.3.pre3

### ISSUE THREAD

**Issue by pencilcheck** [voltrb/volt#215]
When starting up server using `bundle exec volt s` after bundle install today I got the errors below:
```
/Users/pencilcheck/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/volt-0c7d5e622931/lib/volt/server/message_bus/peer_to_peer.rb:121:in `block (2 levels) in connect_to_peers': undefined method `_ips' for nil:NilClass (NoMethodError)
/Users/pencilcheck/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/volt-0c7d5e622931/lib/volt/server/message_bus/peer_to_peer.rb:121:in `block (2 levels) in connect_to_peers': undefined method `_ips' for nil:NilClass (NoMethodError)
Unexpected error while processing request: drbunix:/var/folders/pw/l0w0lnkx72vb82bhfv6hn9y00000gn/T/druby88620.0 - #<Errno::ENOENT: No such file or directory - connect(2) for /var/folders/pw/l0w0lnkx72vb82bhfv6hn9y00000gn/T/druby88620.0>
```

Using volt 0.9.3.pre3 revision `0c7d5e622931cba2324a2abd74b74af647b1cf39`

This occurs on 0.9.3.pre2 as well

**Comment by ryanstout** [comment]
Is this on a new project?

**Comment by pencilcheck** [comment]
Old projects, new projects seems ok.

**Comment by ryanstout** [comment]
Might be related to some sort of setup.  Also, stick with testing on pre2 for now.  I realized after that pre3 has a few issues.
