### ISSUE TITLE
volt/server/websocket/websocket_handler.rb:25:in `call'

### ISSUE THREAD

**Issue by jjman505** [voltrb/volt#244]
All I did was: 

```
gem install volt
volt new volt-todos
cd volt-todos
bundle exec volt server
```

When I navigate to `localhost:3000` in my browser I get the following error in my console:

```
127.0.0.1 - - [08/Jul/2015 20:08:23] "GET / HTTP/1.1" 200 - 0.0040
Unexpected error while processing request: wrong number of arguments (2 for 1)
	/home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/faye-websocket-0.9.2/lib/faye/websocket/api/event_target.rb:20:in `add_listener'
	/home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/websocket-driver-0.6.0/lib/websocket/driver/event_emitter.rb:16:in `on'
	/home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/volt-0.9.4/lib/volt/server/websocket/websocket_handler.rb:25:in `call'
	/home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/rack-1.5.5/lib/rack/builder.rb:138:in `call'
	/home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
	/home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
	/home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
	/home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `call'
	/home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `block in spawn_threadpool'
```

In the client javascript console, I get this error:

```
WebSocket connection to 'ws://localhost:3000/socket' failed: Invalid frame header
app.js:24769 WebSocket Error  Event {}
```

I'm using Ubuntu 14.04, Chrome Version 43.0.2357.132
I get the same behavior in Firefox.

I assume it originates from this line in the traceback: `volt/server/websocket/websocket_handler.rb:25:in 'call'`

**Comment by jjman505** [comment]
Since the latest version of faye-websocket is suspect, I tried adding this line to my gemfile:

```
gem 'faye-websocket', '0.9.2'
```

I ran bundle to reinstall, but on running the server I now get this error and the process ends:

```
home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:526:in `start_server'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/backends/tcp_server.rb:16:in `connect'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/backends/base.rb:63:in `block in start'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `call'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/rack-1.5.5/lib/rack/handler/thin.rb:16:in `run'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/volt-0.9.4/lib/volt/cli.rb:87:in `server'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/volt-0.9.4/lib/volt/cli.rb:135:in `<top (required)>'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/volt-0.9.4/bin/volt:4:in `require'
	from /home/jeremy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/volt-0.9.4/bin/volt:4:in `<top (required)>'
	from /home/jeremy/.rbenv/versions/2.1.4/bin/volt:23:in `load'
	from /home/jeremy/.rbenv/versions/2.1.4/bin/volt:23:in `<main>'
```

**Comment by ryanstout** [comment]
@jjman505 I ran into the same issue on a new project today.  I added issue https://github.com/faye/faye-websocket-ruby/issues/68  Hopefully they will fix it soon.  For now, yea, add the ```gem 'faye-websocket', '0.9.2'``` in your Gemfile

**Comment by ryanstout** [comment]
@jjman505 actually, try this:

gem 'faye-websocket', '0.9.2'
gem 'websocket-driver', '0.5.4'

**Comment by jjman505** [comment]
@ryanstout Works great, thanks!

**Comment by mamantoha** [comment]
@ryanstout thanks! :+1:
