### ISSUE TITLE
Unexpected error while processing request: wrong number of arguments (2 for 1)

### ISSUE THREAD

**Issue by RickCarlino** [voltrb/volt#245]
```
/home/rick/.rvm/gems/ruby-2.2.0/gems/faye-websocket-0.9.2/lib/faye/websocket/api/event_target.rb:20:in `add_listener'
/home/rick/.rvm/gems/ruby-2.2.0/gems/websocket-driver-0.6.0/lib/websocket/driver/event_emitter.rb:16:in `on'
/home/rick/.rvm/gems/ruby-2.2.0/gems/volt-0.9.4/lib/volt/server/websocket/websocket_handler.rb:25:in `call'
/home/rick/.rvm/gems/ruby-2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:138:in `call'
/home/rick/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
/home/rick/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
/home/rick/.rvm/gems/ruby-2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
/home/rick/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `call'
/home/rick/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `block in spawn_threadpool'
```

**Comment by RickCarlino** [comment]
Running Volt 0.9.4

**Comment by ryanstout** [comment]
See https://github.com/voltrb/volt/issues/244  Going to leave this up for now.

**Comment by ryanstout** [comment]
I'm trying to get the gem owner of faye-websocket to fix his gem.  In the mean time, add the following to your gemfile:

```ruby
gem 'faye-websocket', '0.9.2'
gem 'websocket-driver', '0.5.4'
```

**Comment by RickCarlino** [comment]
```
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
You have requested:
  websocket-driver = 0.5.4

The bundle currently has websocket-driver locked at 0.6.0.
Try running `bundle update websocket-driver`
```

**Comment by ryanstout** [comment]
@RickCarlino sorry, then run ```bundle update```

**Comment by ryanstout** [comment]
This should be fixed for new installs.
