### ISSUE TITLE
Errno::ENOENT: No such file or directory

### ISSUE THREAD

**Issue by acrogenesis** [voltrb/volt#290]
I've just installed Volt and I'm following the Todos tutorial, after running `bundle exec volt server` I try to access `localhost:3000` The browser stays `waiting for localhost`. When I exit the volt server I get this error. (I'm using ruby-2.2.2)
```
Volt 0.9.5
                             ,--,           ,----, 
                ,----..   ,---.'|         ,/   .`| 
               /   /   \  |   | :       ,`   .'  : 
       ,---.  /   .     : :   : |     ;    ;     / 
      /__./| .   /   ;.  \|   ' :   .'___,/    ,'  
 ,---.;  ; |.   ;   /  ` ;;   ; '   |    :     |   
/___/ \  | |;   |  ; \ ; |'   | |__ ;    |.';  ;   
\   ;  \ ' ||   :  | ; | '|   | :.'|`----'  |  |   
 \   \  \: |.   |  ' ' ' :'   :    ;    '   :  ;   
  ;   \  ' .'   ;  \; /  ||   |  ./     |   |  '   
   \   \   ' \   \  ',  / ;   : ;       '   :  |   
    \   `  ;  ;   :    /  |   ,/        ;   |.'    
     :   \ |   \   \ .'   '---'         '---'      
      '---"     `---`                              
                                                   
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 500
Listening on 0.0.0.0:3000, CTRL+C to stop
^CUnexpected error while processing request: connection closed
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:578:in `load'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:640:in `recv_reply'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:940:in `recv_reply'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1254:in `send_message'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1142:in `block (2 levels) in method_missing'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1229:in `open'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1141:in `block in method_missing'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1160:in `with_friend'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1140:in `method_missing'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/volt-0.9.5/lib/volt/server/forking_server.rb:204:in `block in call'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/volt-0.9.5/lib/volt/utils/read_write_lock.rb:58:in `with_read_lock'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/volt-0.9.5/lib/volt/server/forking_server.rb:189:in `call'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/volt-0.9.5/lib/volt/server/websocket/websocket_handler.rb:39:in `call'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/builder.rb:138:in `call'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `call'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `block in spawn_threadpool'

Unexpected error while processing request: drbunix:/var/folders/sv/htbd6j1x5pdbjtc6fcsb2vlr0000gn/T/druby14458.0 - #<Errno::ENOENT: No such file or directory - connect(2) for /var/folders/sv/htbd6j1x5pdbjtc6fcsb2vlr0000gn/T/druby14458.0>
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:744:in `rescue in block in open'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:738:in `block in open'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:737:in `each'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:737:in `open'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1248:in `initialize'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1228:in `new'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1228:in `open'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1141:in `block in method_missing'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1160:in `with_friend'
	/Users/Adrian/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1140:in `method_missing'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/volt-0.9.5/lib/volt/server/forking_server.rb:204:in `block in call'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/volt-0.9.5/lib/volt/utils/read_write_lock.rb:58:in `with_read_lock'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/volt-0.9.5/lib/volt/server/forking_server.rb:189:in `call'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/volt-0.9.5/lib/volt/server/websocket/websocket_handler.rb:39:in `call'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/builder.rb:138:in `call'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `call'
	/Users/Adrian/.rvm/gems/ruby-2.2.2/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `block in spawn_threadpool'
```

**Comment by ryanstout** [comment]
What os?  Was this a new project or upgraded from an existing?

**Comment by acrogenesis** [comment]
Sorry for the lat response, this was on Mac OS 10.11, on a new project.

**Comment by vogelbek** [comment]
I too am having this issue.
OSX 10.10.5
Ruby 2.2.2
Todo tutorial app

Only difference is mine was triggered by a timeout instead of killing the server:
`Unexpected error while processing request: druby://mac:XXXXX - #<Errno::ETIMEDOUT: Operation timed out - connect(2) for "mac" port XXXXX>`

It worked great when I followed the tutorial over the weekend, but when I tried to show a buddy at work it was less than impressive.

Any suggestions for where I should start looking for the root cause?
