### ISSUE TITLE
db seed task running in volt console hangs after 500+ store._xyz.create's

### ISSUE THREAD

**Issue by balmoral** [voltrb/volt#315]
Running a task from the volt console to seed database from a csv file: it regularly (but not consistently) hangs around 506/507th line of CSV, which equates to the same number of model creates (in four different collections). 

If `sleep(0.05)` is put after each create call then there is no problem. 

The following is the stack trace when ctrl-c pressed (when hung).

```
Exception in Promise at .sync: Interrupt/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/server/message_bus/peer_to_peer/peer_connection.rb:105:in `push'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/server/message_bus/peer_to_peer/peer_connection.rb:105:in `publish'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/server/message_bus/peer_to_peer.rb:105:in `block in publish'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/server/message_bus/peer_to_peer.rb:102:in `each'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/server/message_bus/peer_to_peer.rb:102:in `publish'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/app/volt/tasks/live_query/live_query_pool.rb:29:in `updated_collection'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/models/persistors/model_store.rb:180:in `save_to_db!'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/models/persistors/model_store.rb:75:in `changed'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/models/helpers/change_helpers.rb:73:in `persist_changes'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/models/helpers/change_helpers.rb:39:in `block in run_changed'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:202:in `call'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:202:in `resolve'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:179:in `>>'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:162:in `^'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:272:in `then'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/models/helpers/change_helpers.rb:24:in `run_changed'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/models/array_model.rb:346:in `block (2 levels) in create_new_model'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:202:in `call'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:202:in `resolve'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:179:in `>>'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:162:in `^'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:272:in `then'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/extra_core/object.rb:46:in `promisify_and_run_method'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/extra_core/object.rb:27:in `then'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/models/array_model.rb:344:in `block in create_new_model'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:202:in `call'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:202:in `resolve'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:179:in `>>'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:162:in `^'
/Users/col/.rvm/gems/ruby-2.2.1/gems/opal-0.8.0/stdlib/promise.rb:272:in `then'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/models/array_model.rb:343:in `create_new_model'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/models/array_model.rb:145:in `create'
/Users/col/dev/workspace/tbs/tbs-volt/app/main/tasks/seed_from_csv.rb:168:in `block in seed_from_csv'
/Users/col/dev/workspace/tbs/tbs-volt/app/main/tasks/seed_from_csv.rb:90:in `loop'
/Users/col/dev/workspace/tbs/tbs-volt/app/main/tasks/seed_from_csv.rb:90:in `seed_from_csv'
/Users/col/dev/workspace/tbs/tbs-volt/app/main/tasks/seed_from_csv.rb:206:in `seed'
(pry):1:in `__pry__'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/pry_instance.rb:355:in `eval'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/pry_instance.rb:323:in `handle_line'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/pry_instance.rb:242:in `catch'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/pry_instance.rb:242:in `block in eval'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/pry_instance.rb:241:in `catch'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/pry_instance.rb:241:in `eval'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/cli/console.rb:19:in `block in repl'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/cli/console.rb:9:in `loop'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/cli/console.rb:9:in `repl'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/repl.rb:38:in `block in start'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/input_lock.rb:61:in `call'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/input_lock.rb:61:in `__with_ownership'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/input_lock.rb:79:in `with_ownership'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/repl.rb:38:in `start'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/repl.rb:15:in `start'
/Users/col/.rvm/gems/ruby-2.2.1/gems/pry-0.10.2/lib/pry/pry_class.rb:169:in `start'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/cli/console.rb:84:in `start'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/cli.rb:39:in `console'
/Users/col/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/col/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/col/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/col/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/cli.rb:182:in `<top (required)>'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/bin/volt:4:in `require'
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/bin/volt:4:in `<top (required)>'
/Users/col/.rvm/gems/ruby-2.2.1/bin/volt:23:in `load'
/Users/col/.rvm/gems/ruby-2.2.1/bin/volt:23:in `<main>'
/Users/col/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/col/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Interrupt: 
from /Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-eae99c12c0b6/lib/volt/server/message_bus/peer_to_peer/peer_connection.rb:105:in `push'
[2] volt(main)> 
```

**Comment by matthew342** [comment]
@balmoral Have noted similar behavior - it seems to be related to the message bus. Try running it with NO_MESSAGE_BUS=true and see if that changes the behavior.

**Comment by balmoral** [comment]
@matthew342 thanks - that solved my problem. But having no message bus raised an error in in `volt/cli/runner` when it attempts to disconnect (I presume from the bus):

```
/Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-d2be5e640eca/lib/volt/cli/runner.rb:14:in `run_file': undefined method `disconnect!' for nil:NilClass (NoMethodError)
        from /Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-d2be5e640eca/lib/volt/cli.rb:104:in `runner'
        from /Users/col/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/col/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/col/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/col/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-d2be5e640eca/lib/volt/cli.rb:182:in `<top (required)>'
        from /Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-d2be5e640eca/bin/volt:4:in `require'
        from /Users/col/.rvm/gems/ruby-2.2.1/bundler/gems/volt-d2be5e640eca/bin/volt:4:in `<top (required)>'
        from /Users/col/.rvm/gems/ruby-2.2.1/bin/volt:23:in `load'
        from /Users/col/.rvm/gems/ruby-2.2.1/bin/volt:23:in `<main>'
        from /Users/col/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/col/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by matthew342** [comment]
Yeah, I've seen that as well - I think it just doesn't check if the bus is connected before calling disconnect in the runner. No harm done (I presume), but would be an easy PR to fix
